# Generated by Django 6.0.2 on 2026-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_mailingsubscription_review_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="Повне ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('delivery_address', models.TextField(verbose_name='Адреса доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Час доставки')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('card', 'Банківська картка')], max_length=10, verbose_name='Спосіб оплати')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('cart_data', models.JSONField(verbose_name='Дані кошика')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('processing', 'В обробці'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
